### ISSUE TITLE
Problem installing - Composer runnig out of memory

### ISSUE THREAD

**Issue by FabioSTI** [aiman1717a/thaana-tinymce-field#1]
Got the following error message, even after updating php.ini to: memory_limit = 512M

PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 4096 bytes) in C:\Proyectos\xxxx-yyyyyy-v2\vendor\composer\autoload_static.php on line 1851

I had to  (in Windows):
Set this environmet var, befor executing composer:

` set COMPOSER_MEMORY_LIMIT=-1 `

and then run the composer require statement:

`composer require aiman/thaana-tinymce-field`

That worked for me.

**Comment by aiman1717a** [comment]
Thank you for informing
This issue is related to the composer and php
Glad it worked out
